//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.601.10.0
//     UI Plugin:   1.4201.17.0
//
//     Project:     Classroom
//     Version:     1.0.0.0
//     Sdk:         CH5:2.16.0
//     Strategy:    Modern
//     IndexOnly:   False
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using Classroom;

namespace Classroom.Main
{

    /// <summary>
    /// DisplayPowerOffConfirm
    /// </summary>
    public partial interface IDisplayPowerOffConfirm 
    {
        object UserObject { get; set; }

        /// <summary>
        /// Event Main.DisplayPowerOffConfirm.Display Off Cancel Button.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> DisplayOffCancelButton_PressEvent;

        /// <summary>
        /// Event Main.DisplayPowerOffConfirm.Display Off Confirm Button.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> DisplayOffConfirmButton_PressEvent;

        /// <summary>
        /// Display-Power-Off-Confirm.Visibility Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DisplayPowerOffConfirm_Visibility_fb(DisplayPowerOffConfirmBoolInputSigDelegate callback);

        /// <summary>
        /// Display-Power-Off-Confirm.Visibility Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DisplayPowerOffConfirm_Visibility_fb(bool digital);

        /// <summary>
        /// Main.DisplayPowerOffConfirm.Display Confirm Power Off Gauge.Lower Touch fb Feedback
        /// </summary>
        /// <param name="callback">The ushort delegate to update the panel.</param>
        void DisplayConfirmPowerOffGauge_LowerTouchfb(DisplayPowerOffConfirmUShortInputSigDelegate callback);

        /// <summary>
        /// Main.DisplayPowerOffConfirm.Display Confirm Power Off Gauge.Lower Touch fb Feedback
        /// </summary>
        /// <param name="callback">The ushort analog to update the panel.</param>
        void DisplayConfirmPowerOffGauge_LowerTouchfb(ushort analog);

        /// <summary>
        /// Main.DisplayPowerOffConfirm.Display Confirm Power Off Gauge.Lower Touch fb Feedback
        /// </summary>
        /// <param name="callback">The short analog to update the panel.</param>
        void DisplayConfirmPowerOffGauge_LowerTouchfb(short analog);
    }

    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="boolInputSig">The <see cref="BoolInputSig"/> joinInfo data.</param>
    /// <param name="displaypoweroffconfirm">The <see cref="IDisplayPowerOffConfirm"/> on which to apply the feedback.</param>
    public delegate void DisplayPowerOffConfirmBoolInputSigDelegate(BoolInputSig boolInputSig, IDisplayPowerOffConfirm displaypoweroffconfirm);
    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="uShortInputSig">The <see cref="UShortInputSig"/> joinInfo data.</param>
    /// <param name="displaypoweroffconfirm">The <see cref="IDisplayPowerOffConfirm"/> on which to apply the feedback.</param>
    public delegate void DisplayPowerOffConfirmUShortInputSigDelegate(UShortInputSig uShortInputSig, IDisplayPowerOffConfirm displaypoweroffconfirm);

    /// <summary>
    /// DisplayPowerOffConfirm
    /// </summary>
    internal partial class DisplayPowerOffConfirm : IDisplayPowerOffConfirm, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion

        #region Joins

        private static class Joins
        {
            /// <summary>
            /// Digital signals,
            /// </summary>
            internal static class Booleans
            {
                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: Main.DisplayPowerOffConfirm.DisplayOffCancelButton.Press
                /// Main.DisplayPowerOffConfirm.Display Off Cancel Button.Press
                /// </summary>
                public const uint DisplayOffCancelButton_PressEvent = 2;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: Main.DisplayPowerOffConfirm.DisplayOffConfirmButton.Press
                /// Main.DisplayPowerOffConfirm.Display Off Confirm Button.Press
                /// </summary>
                public const uint DisplayOffConfirmButton_PressEvent = 3;


                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Main.DisplayPowerOffConfirm.Visibility_fb
                /// Display-Power-Off-Confirm.Visibility
                /// </summary>
                public const uint DisplayPowerOffConfirm_Visibility_fbState = 1;

            }
            /// <summary>
            /// Analog signals.
            /// </summary>
            internal static class Numerics
            {

                /// <summary>
                /// Input or Feedback analog joinInfo from Control System to panel: Main.DisplayPowerOffConfirm.DisplayConfirmPowerOffGauge.LowerTouchfb
                /// Main.DisplayPowerOffConfirm.Display Confirm Power Off Gauge.Lower Touch fb
                /// </summary>
                public const uint DisplayConfirmPowerOffGauge_LowerTouchfbState = 4;

            }
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="DisplayPowerOffConfirm"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal DisplayPowerOffConfirm(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DisplayPowerOffConfirm"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal DisplayPowerOffConfirm(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="DisplayPowerOffConfirm"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>(); 
 
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.DisplayOffCancelButton_PressEvent, onDisplayOffCancelButton_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.DisplayOffConfirmButton_PressEvent, onDisplayOffConfirmButton_Press);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);
        }

        #endregion

        #region CH5 Contract

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> DisplayOffCancelButton_PressEvent;
        private void onDisplayOffCancelButton_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = DisplayOffCancelButton_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> DisplayOffConfirmButton_PressEvent;
        private void onDisplayOffConfirmButton_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = DisplayOffConfirmButton_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public void DisplayPowerOffConfirm_Visibility_fb(DisplayPowerOffConfirmBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DisplayPowerOffConfirm_Visibility_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void DisplayPowerOffConfirm_Visibility_fb(bool digital)
        {
            DisplayPowerOffConfirm_Visibility_fb((sig, component) => sig.BoolValue = digital);
        }

        /// <inheritdoc/>
        public void DisplayConfirmPowerOffGauge_LowerTouchfb(DisplayPowerOffConfirmUShortInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].UShortInput[Joins.Numerics.DisplayConfirmPowerOffGauge_LowerTouchfbState], this);
            }
        }

        /// <inheritdoc/>
        public void DisplayConfirmPowerOffGauge_LowerTouchfb(ushort analog)
        {
            DisplayConfirmPowerOffGauge_LowerTouchfb((sig, component) => sig.UShortValue = analog);
        }

        /// <inheritdoc/>
        public void DisplayConfirmPowerOffGauge_LowerTouchfb(short analog)
        {
            DisplayConfirmPowerOffGauge_LowerTouchfb((sig, component) => sig.ShortValue = analog);
        }

        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "DisplayPowerOffConfirm", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

            DisplayOffCancelButton_PressEvent = null;
            DisplayOffConfirmButton_PressEvent = null;
        }

        #endregion
    }
}
